# This is a basic workflow to help you get started with ActionsAdd commentMore actions

name: deploy

# Controls when the workflow will run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy Container to Local Machine
    runs-on: ubuntu-latest  
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.7  
        with:
          host: 192.168.1.37
          username: G8
          password: venkat123
          debug: true
          script: |
            echo "Hello World"
            
          
