# This is a basic workflow to help you get started with ActionsAdd commentMore actions

name: deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
      steps:
        - name: connect and pull
          run: echo "hello world"
        - name: ssh
          run: ssh ge8/venkat123@ 192.168.1.37 "exit"
