# This is a basic workflow to help you get started with ActionsAdd commentMore actions

name: deploy

# Controls when the workflow will run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy Container to Local Machine
    runs-on: ubuntu-latest  
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1 
        with:
          host: ${{ secrets.HOST }}
          username: G8
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
          debug: true
            
            
          
