# This is a basic workflow to help you get started with ActionsAdd commentMore actions

name: deploy

# Controls when the workflow will run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy Container to Local Machine
    runs-on: ubuntu-latest  
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.7  
        with:
          host: 192.168.1.37
          username: g8
          password: venkat123
          script: |
            docker pull sdondapati/dockerhello:latest
            docker stop testhello || true  # Stop container if running
            docker rm testhello || true    # Remove container if exists
            docker run -d --name testhello -p 80:80 sdondapati/dockerhello:latest # Replace with your 


          
