# This is a basic workflow to help you get started with ActionsAdd commentMore actions

name: deploy

# Controls when the workflow will run


on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy Container to Local Machine
    runs-on: ubuntu-latest  
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1 
        with:
          host: 192.168.1.37
          username: sshuser
          password: venkat123
          port: 22
          script: whoami
          timeout: 1200s
          debug: true
            
            
          
