# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sdondapati/dockerhello:latest
      - 
        name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy to Docker Desktop
        run: |
          docker run -d --name testhello -p 8080:80 sdondapati/dockerhello:latest
