# This is a basic workflow to help you get started with ActionsAdd commentMore actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: sdondapati/dockerhello1:latest
      credentials:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Run some commands
        run: |
          # Commands will run inside the container
          echo "Running inside the container"
          ls -l .  # Access files from mounted volume
